### ISSUE TITLE
Table generation from CSV file failed

### ISSUE THREAD

**Issue by laihz** [wireservice/csvkit#819]
I'm trying to generate a table from a CSV file worked in previous version (0.9.1) but failed after upgrading to 1.0.2 (mentioned in doc but there is no tag so I used the master branch):

`head -n 10000 /path/sample.csv | csvsql -v -d ',' --db mysql://<user>:<passwd>@127.0.0.1:3306/test_schema --table my_test_table
`

The error message is copied below.

```
Traceback (most recent call last):
  File "/home/vagrant/conda/envs/_test_csv/bin/csvsql", line 6, in <module>
    sys.exit(csvkit.utilities.csvsql.launch_new_instance())
  File "build/bdist.linux-x86_64/egg/csvkit/utilities/csvsql.py", line 188, in launch_new_instance
  File "build/bdist.linux-x86_64/egg/csvkit/cli.py", line 114, in run
  File "build/bdist.linux-x86_64/egg/csvkit/utilities/csvsql.py", line 94, in main
  File "build/bdist.linux-x86_64/egg/csvkit/utilities/csvsql.py", line 147, in _failsafe_main
TypeError: to_sql() got an unexpected keyword argument 'create_if_not_exists'

```
After some detective work, I was able to trace the issue to the version mismatch of one of its dependency package "agate-sql". In the "setup.py", it was declared like this:

```
install_requires = [
    ......
    'agate-sql>=0.5.1',
    ......
]

```

When I checked "agate-sql" version 0.5.1 on the Github: https://github.com/wireservice/agate-sql/blob/0.5.1/agatesql/table.py, the "to_sql" method signature looks like this:

`def to_sql(self, connection_or_string, table_name, overwrite=False, create=True, insert=True, prefixes=[], db_schema=None, constraints=True):
`

Only after I switched to the master branch https://github.com/wireservice/agate-sql/blob/master/agatesql/table.py, I can find the missing keyword argument "create_if_not_exists":

`def to_sql(self, connection_or_string, table_name, overwrite=False, create=True, create_if_not_exists=False, insert=True, prefixes=[], db_schema=None, constraints=True):
`

Therefore, I think this is a bug caused by adding a feature in csvkit that is not released by its dependent package.

**Comment by jpmckinney** [comment]
Dupe discussion in #813
